import os
import sys
import feedparser
import re
 
MyFeedsConfig = ['http://freshmeat.net/index.atom']
 
feeds = []  
for feed in MyFeedsConfig:  
    feeds.append(feedparser.parse(feed))  
entries = []
fd =  open('output.html','w')
html = """
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta name="robots" content="noindex,nofollow,noarchive">
<meta http-equiv="Refresh" content="10800">
    <link rel="stylesheet" href="style.css" type="text/css">
    <title>FeedParser-V</title>
</head>
<body id="rawdog">
<div id="header">
<h1>FeedParser</h1>
</div>
<div id="items">
 
</div>
<h2 id="feedstatsheader">Feeds</h2>
<div id="feedstats">
<table id="feeds">
<tr id="feedsheader">
<th>Title</th><th>Description</th><th>URL</th><th>Modification Time</th>
</tr>"""
 
for feed in feeds:  
    for item in feed[ "items" ]:
        i = 100
        sumar = item.summary[i]
        while sumar != ' ':
            i = i + 1
            sumar = item.summary[i]
        sumar = item.summary[:i]
        html += """<tr id="feedsrow"><th>%s</th><th>%s...</th><th><a href="%s">go to page</a></th><th>%s</th></tr>""" % (item.title, sumar, item.links[0]['href'], item.updated)
        #print item.content
        #break
html += """</table>
</div>
<div id="footer">
<p id="aboutrawdog">Generated by
Vivek Sharma
</div>
</body>
</html>"""
 
fd.write('%s' % html.encode('ascii', 'ignore'))
    
fd.close()